### ISSUE TITLE
Modify Config

### ISSUE THREAD

**Issue by controloye** [WebRTSP/Native#1]
I have installed this App using snap from https://snapcraft.io/rtsp-to-webrtsp

I am not able to change config file so I can add my own camera stream instead of already listed streams.
Please guide or publish usage manual.

**Comment by RSATom** [comment]
Streamers are configuring on JavaScript side: https://github.com/WebRTSP/BrowserClient/blob/master/Config.js
But unfortunately in `rtsp-to-webrtsp` snap `Config.js` is placed inside snap image and is read-only. So you just can't modify it without create your own snap. I think I should add ability provide custom URL to HTML/JS side.

Other possible solution can be run your own http server with modified `Config.js`

**Comment by RSATom** [comment]
And you are right, it worth add some docs...

**Comment by controloye** [comment]
Still need some documentation for beginners that how to run their own http server with modified Config.js

In my opinion SNAP is best and easiest method. You need to define USER_DATA path so config can be placed on that path.

**Comment by RSATom** [comment]
I think I just should add ability configure Streamers with config file too. And maybe add some flag to enable/disable ability accept URLs from client (HTML/JS) side. I'll try to find some time for it on weekend.

**Comment by controloye** [comment]
as you said, config.js can be managed if we have own http server.

here is working example with snap ( perfect - but with predefined config )

http://server2.eyecloud.ro:5080/

then I placed BrowserClient  under my http server ( apache ) at

http://server2.eyecloud.ro/BrowserClient/

it is running on same server where snap version is working that means ws://server2.eyecloud.ro:5554  is also active but
I am getting this message on inspect element console

Loading failed for the module with source “http://server2.eyecloud.ro/BrowserClient/WebRTSP.mjs”. BrowserClient:8:1
Uncaught (in promise) TypeError: error loading dynamically imported module
rtsp://ipcam.stream:8554/bars BrowserClient:22:46
![image](https://user-images.githubusercontent.com/20957517/101518815-39ad2380-39a4-11eb-9d59-e70729d28472.png
![webrtsp](https://user-images.githubusercontent.com/20957517/101518939-606b5a00-39a4-11eb-8e25-07e4b90b5c3f.jpg)
)

**Comment by RSATom** [comment]
Browsers just can't import `.mjs` files (JavsScript modules) if HTTP server just not provide correct MIME type for it. I don't know how exactly it can be done with Apache, but you should assign `application/javascript` MIME type to `.mjs` files there.

**Comment by controloye** [comment]
Thanks for tip

I have added following line and it worked - perfect :-)

        AddType application/javascript .mjs

**Comment by RSATom** [comment]
@controloye I've added ability configure streaming sources with config, and disabled reastream client url by default. I mean you test build should break after next snap update.

**Comment by RSATom** [comment]
Also, to get default config you should do `snap remove` and `snap install` since on `snap refresh` initial config create does not happen.

**Comment by RSATom** [comment]
Closing as resolved
